### PR TITLE
Coder: Update Docker Port

### PR DESCRIPTION
**Pull request by zZebrahz**
Coder updated the internal docker port, reflecting that change here.

### CODE REVIEW

**Comment by desimaniac** [comment]
Line 42 also needs changing.

**Comment by zZebrahz** [comment]
> Line 42 also needs changing.

The change was made for the internal docker port.  If you'd like I could change both of the external ports.

**Comment by desimaniac** [comment]
That's how reverse proxy works.

**Comment by zZebrahz** [comment]
I learned something new today, I always thought the VIRTUAL_PORT was for the host port not the container port (in the case, for instance that you needed to expose two containers that both exposed their services to port 80) making change now.

**Pull request merged**
