### PR TITLE
Conreq

### PR DESCRIPTION
**Pull request by kungfoome**
# Description

Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Ran the new role with success

# New Role Checklist:

- [x] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [x] I have updated the header in any files I may have used as templates with my own information
- [x] I have added my new role to `appveyor.yml`
- [x] I have added my new role to `community.yml`
- [x] I have verified that any Docker images used are current and supported.
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by saltydk** [comment]
You should use an up to date version of the repo when submitting a PR.

**Comment by kungfoome** [comment]
Oh sorry, i was going off of develop. Do you want me to resubmit based on master?

**Comment by saltydk** [comment]
No, you need to use a recent version of develop.

**Comment by kungfoome** [comment]
@saltydk I see what i did. I thought i checked out develop. I was still on master. Let me merge and resubmit

**Pull request closed without merging**
