### PR TITLE
Adding Firefly III service

### PR DESCRIPTION
**Pull request by mariosemes**
Firefly III service added as role.

# Description

Adding Firefly III to the community repo. Firefly III is a free and open source personal finance manager.
More about it here.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [X] Ubuntu 18.04 headless dedicated server with working CB
- [X] Ubuntu 18.04 headless VM with fresh installed CB

# New Role Checklist:

- [X] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [X] I have updated the header in any files I may have used as templates with my own information
- [X] I have added my new role to `appveyor.yml`
- [X] I have added my new role to `community.yml`
- [X] I have verified that any Docker images used are current and supported.
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by sdewolf-be** [comment]
Hello, the installation won't work anymore, i think the docker image url has changed.

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pulling image jc5x/firefly-iii:latest - 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=jc5x%2Ffirefly-iii: Not Found (\"pull access denied for jc5x/firefly-iii, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\")"}
`

Any chance to update the yaml?

Thanks :)

**Comment by owine** [comment]
Is there a specific replacement image that should be used? There appears to be an official container but no notes about why the official was not used.

**Comment by sdewolf-be** [comment]
Hello owine and thanks for such a quick reply. Unfortunatly, i have no idea.. I guess the official one (fireflyiii/core:latest) ?

Cheers,

**Comment by saltydk** [comment]
> Is there a specific replacement image that should be used? There appears to be an official container but no notes about why the official was not used.

It was just renamed.

**Pull request merged**
