### PR TITLE
Add Overseerr role

### PR DESCRIPTION
**Pull request by JackDallas**
# Description

Added [Overseerr](https://github.com/sct/overseerr) a new Ombi-like request app for plex, radarr and sonarr

# How Has This Been Tested?

Ran install start to finish twice on my machine

# New Role Checklist:

- [x] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [x] I have updated the header in any files I may have used as templates with my own information
- [x] I have added my new role to `appveyor.yml`
- [x] I have added my new role to `community.yml`
- [x] I have verified that any Docker images used are current and supported.
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by chazlarson** [comment]
Seems a little early to add this to community.

**Comment by JackDallas** [comment]
> 
> 
> Seems a little early to add this to community.

I was testing it out and made a role anyway to do that, so far it's working pretty well for me but I'm happy to leave this as a draft for a bit to confirm stability ?

**Comment by chazlarson** [comment]
The github notes "Overseerr is currently under very heavy, rapid development and things are likely to break often".  I'd rather let people who are interested in using something like that go through the exercise themselves rather than providing an easy install for it.

Radarrv3 didn't get added until the devs suggested it was ready for widespread use, so this seems like the same sort of thing.

There are already two, maybe three, request systems available through cloudbox.

**Comment by saltydk** [comment]
I've sent a pull request https://github.com/sct/overseerr/pull/278 so that the container exposes the port. I don't want any more localhost bindings if I can help it.

**Comment by chazlarson** [comment]
Install fails on Cloudbox develop branch due to unquoted values:
```
      UMASK: 002
...
      VIRTUAL_PORT: 3000
```
need to be:
```
      UMASK: "002"
...
      VIRTUAL_PORT: "3000"
```

**Review by saltydk — APPROVED** [review]

**Pull request merged**
