### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by h3nchman24**
Please review this template and edit it as appropriate.  It's not been provided as a thing to ignore.  If there are things that don't apply, remove them.  Don't just check boxes for the sake of checking boxes.  Remove this paragraph and the related thing below.

# Description

Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# New Role Checklist:

- [ ] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [ ] I have updated the header in any files I may have used as templates with my own information
- [ ] I have added my new role to `[COMMUNITY REPO ROOT]/.github/workflows/ci.yml`
- [ ] I have added my new role to `community.yml`
- [ ] I have verified that any Docker images used are current and supported.
- [ ] I have made corresponding changes to the documentation
- [ ] This line is still here because I didn't bother to read to the end

### CODE REVIEW

**Comment by chazlarson** [comment]
Perhaps update the template with what this is and does and how it was tested?

**Comment by Banjer** [comment]
Making this change will break current installations of Tdarr, and might even not create a proper fresh installation due to the changes. See https://github.com/Cloudbox/Community/pull/322 for a bit more information.
I have been looking in upgrading the package, and i think the best way to go would be to create a seperate tdarr2 tag.
However, i moved away from using both tdarr and cloudbox, so can't realy help nowadays.

**Comment by kungfoome** [comment]
I actually have a tdarrv2 as @Banjer suggested. I can make a PR for this. It separates it out into tdarr and tdarr node. Been using it like this for a while and haven't had issues. 

https://github.com/kungfoome/Community/tree/master/roles/tdarrv2-node/tasks

https://github.com/kungfoome/Community/tree/master/roles/tdarrv2/tasks

**Comment by owine** [comment]
#402

**Pull request closed without merging**
