### PR TITLE
Fix permission issue for Jellyfin

### PR DESCRIPTION
**Pull request by yassineim**

### CODE REVIEW

**Comment by RXWatcher** [comment]
This actually breaks Jellyfin from my testing. It creates files in /opt/jellyfin that are owned by root.

Was there an issue you were trying to correct with this method?

**Comment by desimaniac** [comment]
I'm pretty sure this also required switching docker image to LSIO's.

**Comment by desimaniac** [comment]
Can you rebase with develop branch? Added in mariadb role so it wont error.

**Comment by yassineim** [comment]
OK I will

**Comment by desimaniac** [comment]
Fixed with 75223d7

**Pull request closed without merging**
