### PR TITLE
Add role: makemkv

### PR DESCRIPTION
**Pull request by Mnk3y**

### CODE REVIEW

**Comment by owine** [comment]
Probably makes sense to either create a htpasswd for the subdomain or it looks like the container supports defining `VNC_PASSWORD` as an env.

**Comment by saltydk** [comment]
Remove the localhost published ports unless there is an actual reason for using it.

**Comment by saltydk** [comment]
Closing due to lack of response by the dev and docker image does not expose the port so couldn't edit it to comply with my own request.

**Comment by Norin-Radd** [comment]
is it possible to add this role? does this image comply with the request?

https://hub.docker.com/r/jlesage/makemkv

**Comment by saltydk** [comment]
That is the same image and you can expose it at runtime.

**Comment by Norin-Radd** [comment]
Thanks for the reply.

Any alternative to remux on cloudbox? 
probably eac3to? theres 2 docker images available. 

would appreciate your help and opinion.

**Comment by saltydk** [comment]
I suggest asking on their discord. I do not use Cloudbox anymore.

**Comment by Norin-Radd** [comment]
ok, thank you... eventually ill move to saltbox one day... didnt do it because of wiki...

**Comment by saltydk** [comment]
Chaz has done a lot of work on it so it is improving.

**Pull request closed without merging**
