### PR TITLE
Moviematch

### PR DESCRIPTION
**Pull request by jolbol1**
# Description

MovieMatch connects to your Plex server and gets a list of movies (from any libraries marked as a movie library).

As many people as you want connect to your MovieMatch server and get a list of shuffled movies. Swipe right to 👍, swipe left to 👎.

If two (or more) people swipe right on the same movie, it'll show up in everyone's matches. The movies that the most people swiped right on will show up first.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Ubuntu 18.04 headless machine running cloudbox
- [x] Several months and multiple users

# New Role Checklist:

- [x] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [x] I have updated the header in any files I may have used as templates with my own information
- [x] I have added my new role to `appveyor.yml`
- [x] I have added my new role to `community.yml`
- [x] I have verified that any Docker images used are current and supported.
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by chimpy** [comment]
Hey @jolbol1

Is moviematch with CB working for you? When I open a room, I see "Loading movies..." indefinitely. Nothing interesting in the debug logs.
Browsing through moviematch's issues (https://github.com/LukeChannings/moviematch/issues/26) it looks like a DNS/networking thing? Does the CB implementation work correctly with the CB plex.URL ? I'm not sure how to test it with the IP:port as it's not in the settings.yml.

Thanks!

**Comment by jolbol1** [comment]
> Hey @jolbol1
> 
> Is moviematch with CB working for you? When I open a room, I see "Loading movies..." indefinitely. Nothing interesting in the debug logs.
> Browsing through moviematch's issues ([LukeChannings/moviematch#26](https://github.com/LukeChannings/moviematch/issues/26)) it looks like a DNS/networking thing? Does the CB implementation work correctly with the CB plex.URL ? I'm not sure how to test it with the IP:port as it's not in the settings.yml.
> 
> Thanks!

Works fine for me. But I use https://plex.mydomain.com

**Comment by chimpy** [comment]
Sure, I use the same URL too, sorry if I wasn't clear.

**Comment by jolbol1** [comment]
It works for me using http://plex:32400 as well. 

To test this you have to change the environment variable on portainer, and ensure moviematch is still on the cloudbox network. Are you able to do this? If not I'll try another way

**Comment by chimpy** [comment]
If you don't mind giving me a couple of commands, or directing me in portainer, sure I can do it :)

**Comment by jolbol1** [comment]
I've created a pull request for it now, so once thats approved re run the tag.

**Pull request merged**
