### PR TITLE
added overseerrx role

### PR DESCRIPTION
**Pull request by RaR0CH**
# Description

[Overseer](https://overseerr.dev/)

I use multiple oversseerr containers for multiple languages.
That's why I think it's useful to have this role.

# How Has This Been Tested?

- [x] I have tested it by running the ansible role on my current server.
- [x] I have by running the ansible role on a freshly installed server.

# New Role Checklist:

- [x] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [x] I have updated the header in any files I may have used as templates with my own information
- [x] I have added my new role to `appveyor.yml`
- [x] I have added my new role to `community.yml`
- [x] I have verified that any Docker images used are current and supported.
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by chazlarson** [comment]
There are no specifics in this description. Did you just check all the boxes without even reading it?

**Comment by chazlarson** [comment]
Seems like "Test A" and "Test B" need to be revamped.

```
TASK [overseerrx : Execute overseerrx roles] ***********************************
Tuesday 16 March 2021  18:51:46 +0000 (0:00:00.046)       0:00:01.901 ********* 
fatal: [localhost]: FAILED! => {"reason": "Syntax Error while loading YAML.\n  but found another document\n\nThe error appears to have been in '/home/appveyor/projects/community/roles/overseerrx/tasks/template.yml': line 12, column 1, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#########################################################################\n---\n^ here\n"}
fatal: [localhost]: FAILED! => {"reason": "Syntax Error while loading YAML.\n  but found another document\n\nThe error appears to have been in '/home/appveyor/projects/community/roles/overseerrx/tasks/template.yml': line 12, column 1, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#########################################################################\n---\n^ here\n
```

**Comment by chazlarson** [comment]
That description above really needs to be edited to contain something meaningful and accurate.  Right now it's just the template with all the boxes checked, 

What is the role?
How did you test this?
Did you actually update any documentation?

**Comment by RaR0CH** [comment]
Sorry, I did not read correctly, I have now fixed the code and the description.
I wanted to wait until the check is finished.

Tell me, If there's anything missing.

**Pull request merged**
