### PR TITLE
Add role: ubooquity - comics server

### PR DESCRIPTION
**Pull request by theotocopulitos**
Ubooquity is a comics server (in the fashion of calibre for books)

### CODE REVIEW

**Comment by Migz93** [comment]
Please rebase to develop

**Comment by Migz93** [comment]
This doesn't quite work as expected. Browsing to "ubooquity.{{ user.domain }}" gives an error page.  I have to manually add "/ubooquity" onto the end of the URL to get anywhere. 
Is this something that can be fixed/changed as it'll confuse most people that may use this?

**Comment by theotocopulitos** [comment]
You are right... I cannot see a way to do so, that's the same when running locally or not in docker... That's why I added this info in the "readme.md" file:

ubooquity - comics server and online reader (ubooquity.your.server/ubooquity for main page / your.ip:2203/ubooquity/admin for admin)

**Comment by Migz93** [comment]
Hadn't noticed that on the README.md. That will do for now. If we find people constantly getting confused we can look to create a wiki page for it.

**Pull request merged**
