### PR TITLE
CouchPotato: Initial Role Addition

### PR DESCRIPTION
**Pull request by javi11**

### CODE REVIEW

**Comment by Migz93** [comment]
"Couchpota" isn't a thing, can you correct the various references to "couchpotato"

**Comment by javi11** [comment]
Yes sure, didn't notice sorry :P

**Comment by javi11** [comment]
@Migz93 done, sorry for taking me so long ;)

**Comment by desimaniac** [comment]
There are still references to that name in the role.

**Comment by javi11** [comment]
@desimaniac Done :S

**Comment by desimaniac** [comment]
Downloads mount could still use some tweaking but will merge for now.

**Pull request merged**
