### PR TITLE
Added role: deemixrr

### PR DESCRIPTION
**Pull request by TheUltimateC0der**

### CODE REVIEW

**Review by chazlarson — CHANGES_REQUESTED** [review]
Title needs an edit:
` Title:         Community: TheLounge Role    `

**Comment by TheUltimateC0der** [comment]
Done!

**Review by chazlarson — CHANGES_REQUESTED** [review]
Needs appveyor.yml and community.yml updates.

https://github.com/Cloudbox/Community/wiki/Contribute

**Comment by chazlarson** [comment]
There's an appveyor build error:

https://ci.appveyor.com/project/Cloudbox/community/builds/35245664

```
ERROR! Syntax Error while loading YAML.
  found unacceptable key (unhashable type: 'AnsibleMapping')
The error appears to have been in '/home/appveyor/projects/community/roles/deemixrr/tasks/main.yaml': line 71, column 28, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
      Hangfire__DashboardPath: /autoloaderjobs
      Hangfire__Password: {{ user.pass }}
                           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:
    with_items:
      - {{ foo }}
Should be written as:
    with_items:
      - "{{ foo }}"
Build exited with code 4
```

**Comment by TheUltimateC0der** [comment]
@chazlarson I fixed the errors, but the latest build seems to fail for an unknown reason: https://ci.appveyor.com/project/Cloudbox/community/builds/35251383 I cannot find the error

**Comment by TheUltimateC0der** [comment]
Oh ... I found the error : `Build execution time has reached the maximum allowed time for your plan (60 minutes).`

**Comment by saltydk** [comment]
I don't think I can manually start a new build on appveyor (probably only desi?). I have been looking into self-hosting appveyor but never played much with Hyper-V.

**Comment by TheUltimateC0der** [comment]
So without a successfull build, this PR cannot get accepted ?

**Comment by saltydk** [comment]
I'm not a maintainer of this repo so I can't speak to that. But off the top of my head I am wondering why you would use a 2 year old and seemingly deprecated image for this solution when we already have mariadb included. From a CB perspective it seems like a needless addition unless it adds something useful (feel free to correct me on this notion by the way). This is compounded for me since you store the DB data inside the deemixrr folder meaning the intent is not to be useful to the ecosystem but to serve a purpose just for this role.

Personally I'd change the /mnt/unionfs mount to just /mnt since that includes unionfs already and allows for non-default structures to function easier without having to modify the container.

These are just my thoughts though so take them however you'd like as I am not one of the repo admins.

**Comment by saltydk** [comment]
You'll have to split up the containers if you want this merged. Change the volume mount from unionfs to just /mnt since that is the standard I'd prefer.

**Comment by saltydk** [comment]
Closing this since there has been to response to the changes requested. You can reopen it if you decide to implement said changes.

**Pull request closed without merging**
