### PR TITLE
added readarr role

### PR DESCRIPTION
**Pull request by claym**

### CODE REVIEW

**Comment by owine** [comment]
Great start - a couple of notes

1) Please check the docker image tag, I don’t think the unstable tag is still valid on hotio images
2) I believe the correct port is 8787 for the VIRTUAL_PORT env
3) I don’t know if the blank line on line 50 will sit right with ansible
4) Please add the tag to appveyor.yml so the CI can test the role

**Comment by saltydk** [comment]
At least test things before you submit them. The only available tag for that image is currently nightly. Personally I think this is more along alpha than beta given all the warnings about updates may require database wipes and I am not sure the time is right for this particular piece of software to join the repo.

**Comment by claym** [comment]
> At least test things before you submit them. 

I did! I have it up and running as we speak. I just search, downloaded, and post processed a book.

>The only available tag for that image is currently nightly. Personally I think this is more along alpha than beta given all the warnings about updates may require database wipes and I am not sure the time is right for this particular piece of software to join the repo.

Fair enough. I can sit on this one for a while.

**Comment by claym** [comment]
> 1. Please check the docker image tag, I don’t think the unstable tag is still valid on hotio images

This was the recommended one from the [Readarr install page](https://github.com/Readarr/Readarr/wiki/Installation#docker). But as @saltydk mentioned, we may be ahead of the curve on this. 
> 2. I believe the correct port is 8787 for the VIRTUAL_PORT env

You're right, I missed this one.

> 3. I don’t know if the blank line on line 50 will sit right with ansible

Nope, it's good - I've run it several times, and it's good. Also, copied this from the komga file, as recommended. It has the [empty line in a similar spot.](https://github.com/Cloudbox/Community/blob/develop/roles/komga/tasks/main.yml#L47)

> 4. Please add the tag to appveyor.yml so the CI can test the role

Wasn't aware of this being in there - I'll add it. Thanks!

**Comment by saltydk** [comment]
> > At least test things before you submit them.
> 
> I did! I have it up and running as we speak. I just search, downloaded, and post processed a book.
> 
> > The only available tag for that image is currently nightly. Personally I think this is more along alpha than beta given all the warnings about updates may require database wipes and I am not sure the time is right for this particular piece of software to join the repo.
> 
> Fair enough. I can sit on this one for a while.

I suppose I should say that you should've tested it better. The version would have told you the image was old since it was changed over a month ago.

**Comment by claym** [comment]
I literally used the tag recommended by the [Readarr install instructions](https://github.com/Readarr/Readarr/wiki/Installation/ac5b01208e46ce8e5ed98543dd64298dae2745fa).

I added the app via normal ansible-playbook process. Went through the configuration. Imported my existing library. Searched for, found, downloaded, imported a book. It all worked as expected. I'm not sure how I could have "tested it better".

I just checked with them in Discord, they said use "nightly". So yes, we may be a bit early here, as they are in "pre-alpha". I'll close the PR and resubmit once they get out of pre-alpha.

**Pull request closed without merging**
