### PR TITLE
Added pyload role

### PR DESCRIPTION
**Pull request by Tr4il**
Added a pyload role.
At this time I am unable to figure out how to apply the credentials in the cloudbox settings to this container. Default credentials are admin/pyload.

### CODE REVIEW

**Comment by desimaniac** [comment]
Should always rebase before pushing commits. You took out plex2 from appveyor. Also add in a banner (see my example in plex2).

**Comment by desimaniac** [comment]
Also does the port need to be exposed ?

**Comment by desimaniac** [comment]
Also, you should use the variable for uid/guid

**Comment by Tr4il** [comment]
Thanks for the pointers, I'll close the pull request for now, fix the issues when I have some time in the coming week and I'll make another one.

**Comment by desimaniac** [comment]
You could have also left this one open and made the changes to this one.

**Pull request closed without merging**
