### PR TITLE
Tdarr pinned to 1.3003 release

### PR DESCRIPTION
**Pull request by Banjer**
# Description

On Sunday 31st Jan, this container (tdarr:latest) will be replaced with Tdarr v2. To keep using this exact container, use tag 1.3003.
If you're coming from V1, unfortunately V2 uses a new database and there have been a lot of changes so you'll need to start fresh.
More info: http://tdarr.io/docs/

# How Has This Been Tested?

- [x] Tested container creation by running the tag 
- [X] Check version in webinterface 
- [x] Had it transcode a video file

### CODE REVIEW

**Comment by saltydk** [comment]
Not sure hardcoding the tag to V1 is the way to go. Outside of a toggle or smart version detection I don't see a reason to merge this.

**Comment by Banjer** [comment]
Working on V2, but the differences are (to) big, volume mappings etc are changing. Updating a current v1 container to v2 will break stuff,

**Comment by saltydk** [comment]
Is V2 going to be broken for new installs using the roles current format?

**Comment by saltydk** [comment]
At any rate, you need to rebase this to develop if you want it merged.

**Comment by Banjer** [comment]
Making a new pull request

**Pull request closed without merging**
