### PR TITLE
Qbittorrentx

### PR DESCRIPTION
**Pull request by kromo-s**
Qbittorrentx role for multiple qbittorrrent instances.
I hope everything works out this time...

### CODE REVIEW

**Comment by saltydk** [comment]
I could be wrong but I don't think you'll have much luck with those port mappings.

**Comment by kromo-s** [comment]
These were the ones I used to get it working.

**Comment by saltydk** [comment]
Torrent clients can work passively but that doesn't mean it works right.

**Comment by saltydk** [comment]
Closing this as improper port mappings are not going to get merged (wrong ports will get reported to the trackers). Feel free to take another crack at it.

**Pull request closed without merging**
