### PR TITLE
Embystats role

### PR DESCRIPTION
**Pull request by satzisa**

### CODE REVIEW

**Comment by maximuskowalski** [comment]
I had a working role with the newer image if you go back a week or so you should be able to find it, otherwise you can copy from my testing repo here https://github.com/maximuskowalski/clockbox/blob/develop/roles/embystats/tasks/main.yml

I deleted this role primarily because it appears to run as root, PUID/GUID is not passable secondly, the image name changes, and thirdly, occasionally the wrong image is uploaded (windows instead of linux recently). If you add this you should make it clear that it is an alpha work in progress and very fluid for now.

**Comment by satzisa** [comment]
> 
> 
> I had a working role with the newer image if you go back a week or so you should be able to find it, otherwise you can copy from my testing repo here https://github.com/maximuskowalski/clockbox/blob/develop/roles/embystats/tasks/main.yml
> 
> I deleted this role primarily because it appears to run as root, PUID/GUID is not passable. Secondly, the image name changes, and thirdly, occasionally the wrong image is uploaded (windows instead of linux recently). If you add this you should make it clear that it is an alpha work in progress and very fluid for now.

Looks like I'm having the same image(uping/embystat:nightly-ubuntu-x64) as yours. Permission should be good now I've changed the permission after created the container. Works fine on my local. I will try to monitor the embystat GitHub for future changes.  you can try this on your local & let me know if there are any corrections.

**Comment by maximuskowalski** [comment]
I don't actually use it anymore, compatibility broke at one stage after an emby update and I just gave up on it.  Desimaniac wanted it fixed so I fixed it but then thought running as root probably wasn't appropriate or something I wanted to be responsible for. Just saw the failed check and thought it might be helpful. Probably should have looked at build failure reason instead.

**Comment by maximuskowalski** [comment]
Ok, looking at the failure it looks like it's actually one of my other roles that is failing on you.
`Running Tag: asshama`
Not sure what has broken it but feel free to delete that role to get your check passed.

**Pull request merged**
