### PR TITLE
New role: Qbittorrentvpn

### PR DESCRIPTION
**Pull request by bonny1992**
Creating as a draft - requires testing, please provide comments
I hope I have done everything correctly.

### CODE REVIEW

**Comment by bonny1992** [comment]
Is the new url https://www.privateinternetaccess.com/openvpn/openvpn-nextgen.zip or https://www.privateinternetaccess.com/openvpn/openvpn.zip ?

**Comment by chazlarson** [comment]
Does this role work locally in your environment?

**Comment by bonny1992** [comment]
@chazlarson 
Yes it works, but PIA changed the naming of their files, from "New Zealand.ovpn" to "new_zealand.ovpn" without me noticing.

I use wireguard, which doesn't require the .ovpn file so I didn't notice it right away.

I'll push asap a modification of the default setting file.

**Comment by chazlarson** [comment]
My point is that this sort of thing should be tested locally, not via repeated pushes to see if the automated build fails.

**Comment by bonny1992** [comment]
Sorry I'm not used to contribute to larger projects.
I corrected the wrong setting, sorry...

**Pull request merged**
