### PR TITLE
Added Calibre role, linuxserver.io based calibre docker image.

### PR DESCRIPTION
**Pull request by AJohnsonCHC**
Added  a new calibre role using a linuxserver.io based calibre docker image. With this new image the old calibre-rdp role is deprecated and no longer needed.

The old image is no longer maintained and hasn't been udpated in over a year.

### CODE REVIEW

**Comment by desimaniac** [comment]
Could we leave the other roles unchanged for now? For those that are still using those containers.

**Comment by AJohnsonCHC** [comment]
Sure thing, Although I was going to make changes to calibre-web as well. I'm going to be changing calibre to have books locally first, then copy books into the unionfs as a backup. Currently storing books in the unionfs breaks the calibre database (atleast for me I haven't talked to other users about this).

I'll create a new role calibre-new containing my changes to calibre, and calibre-web as a single role.

**Comment by pr0blaze** [comment]
I'm still messing with moving to this setup locally.
Probably worthwhile including the mod layer (https://github.com/linuxserver/docker-calibre-mod)

**Comment by desimaniac** [comment]
> Could we leave the other roles unchanged for now? For those that are still using those containers.

If you add a copy of the calibre-rdp folder back, we can merge this i think.

**Comment by BluebonnetSK** [comment]
Can you comment why you are now adding the library into the /opt folder?  That is just not practical if a user has a sizable library, and doesn't fit with the cloudbox way of storing media.   I do see you added a cron in there to copy it regularly, but I would not want my library in /opt as I use a mergerfs union to keep the database local and books on a gdrive mount.

**Comment by AJohnsonCHC** [comment]
Honestly unfamiliarity with mergerfs and the cloudplow service. I'll make some more changes according to your feedback thank you.

**Comment by Migz93** [comment]
If you could make the change highlighted by SK then we can look at possibly merging this in.

In short to change this
`"/opt/calibre/library:/library"`
to something more like this
`"/mnt/unionfs/Media/Calibre:/library"`

and possibly even add
`/mnt:/mnt`
which would allow people to place their libraries wherever they wish within /mnt

**Comment by Migz93** [comment]
Actually it looks like SK has made the changes and raised a separate PR #235 , I'll close this request as that will be the PR to be reviewed.

**Pull request closed without merging**
