### PR TITLE
New Role: Cubecoders AMP

### PR DESCRIPTION
**Pull request by QuickShotx**
Application Management Panel - AMP

Manages many different game servers.  

7 Days to Die
ARK: Survival Evolved
ARMA III
Counter-Strike 1.6
Counter-Strike Source
Counter-Strike Global Offensive
Factorio
Garry's Mod
Insurgency (2014)
Left 4 Dead (2)
Minecraft Bedrock/Java/Pocket Edition
Rust
Space Engineers
StarBound
Team Fortress 2
The Forest

### CODE REVIEW

**Comment by desimaniac** [comment]
The 8080 might be an issue with other containers. Can it not work behind reverse proxy ie subdomain without the port being open?

**Comment by QuickShotx** [comment]
Yup, it should work just fine through the sub domain.   I removed 8080 from the role

**Comment by Migz93** [comment]
Need the role added to appveyor.yml so that it can be tested properly.

Also copy/pasting a message I asked to Discord in case you're able to answer some of these questions.
> Looks like you need a license to get it to even start so I can't test it. Ideally need it tested beforehand, also be nice to see what the paths are like, it seems like its going to dump all the data into /opt which would mean a bunch of large game files in there? Also curious to know how it works with only the port 25565 passed through which looks like only Minecrafts port? Any other games would require the user to edit the ports to get the game to work?

**Comment by QuickShotx** [comment]
> it seems like its going to dump all the data into /opt which would mean a bunch of large game files in there?

Correct.  All of the gamedata would be saved into /opt/ampdata/.    This could be added as an option, but Minecraft installs are generally pretty small.  I could see an issue with other types of servers. 

> Also curious to know how it works with only the port 25565 passed through which looks like only Minecrafts port? Any other games would require the user to edit the ports to get the game to work?

Correct.

**Comment by Migz93** [comment]
Closing this one following our discussion on discord. It looks like a great tool and would be fantastic to use but theres no simple way of managing the various ports that may need to be opened for all the different game servers.

**Pull request closed without merging**
