### PR TITLE
Paperless ng

### PR DESCRIPTION
**Pull request by jolbol1**
# Description

Please include a summary of the change and which issue is fixed if any. Please also include relevant motivation and context. List any dependencies that are required for this change.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Ubuntu 18.04 headless dedicated server with working CB
# New Role Checklist:

- [x] I have reviewed the [Contribute page in the wiki](https://github.com/Cloudbox/Community/wiki/Contribute)
- [x] I have updated the header in any files I may have used as templates with my own information
- [x] I have added my new role to `appveyor.yml`
- [x] I have added my new role to `community.yml`
- [x] I have verified that any Docker images used are current and supported.
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by saltydk** [comment]
This is not a real solution for the "cloudplow" problem.
```yaml
- name: Create blank file - Stops Cloudplow deleting empty dir
  file: "path={{ item }} state=touch mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /mnt/unionfs/Media/Documents/paperless/media/cloudplow.dont.delete_HIDDEN
    - /mnt/unionfs/Media/Documents/paperless/consume/cloudplow.dont.delete_HIDDEN
    - /mnt/unionfs/Media/Documents/paperless/export/cloudplow.dont.delete_HIDDEN
```
 
 It assumes some things about the users configuration that you can't really depend on. It would be preferred that you instruct users how to setup cloudplow/crop to avoid issues specific to this container. Like the "remove_empty_dir_depth" parameter in cloudplow.

When creating folders through ansible I'd prefer if you used local over unionfs just to avoid weird things happening when people use weird mergerfs configurations and forget setting NC/RO flags.

I'm confused as to why you're still including PUID/PGID when the container uses USERMAP_UID/USERMAP_GID per the documentation, any particular reason for that or just trying out things and seeing if they stick?

You're exposing the port during runtime but it is already exposed in the dockerfile?

Have you checked if the redis/postgres containers actually support the PUID/PGID ENVs?

**Comment by jolbol1** [comment]
Fixed as per your comments.

I have not found any documentation regarding PUID and PGID for the postgres/redis containers. The env variables seem limited on these.

Further, for cloudplow and others I have added a note at the end. I plan on adding docs to this. Basically the consume folder shouldnt be uploaded as its only a processing folder, and files should be moved out when applicable.

**Comment by saltydk** [comment]
AppVeyor keeps timing out on the user creation step. Are you sure it works?

**Comment by jolbol1** [comment]
Did earlier. Maybe I do need the 60s wait for some machines. Will review when I get home.

**Comment by jolbol1** [comment]
The script seems to hang a little bit when rerunnig it as the user creation command errors out as the user already exists. Besides that it seems to be working for me.

Not sure why it hangs in appveyor. Im unable to test on a new machine.

**Comment by jolbol1** [comment]
Added a timeout for the user creation. If after 120s it has not worked I fall back to sending them a message.

**Comment by jolbol1** [comment]
added wiki at https://github.com/Cloudbox/Community/wiki/Paperless-Ng

Apologies as I didnt realize this would go live lol.

**Comment by jolbol1** [comment]
I believe I found the error in the end. The user creation script was getting thrown in a loop. This is because the script tries to warn you off various things such as a weak password etc: 
`"userout.stdout_lines": [
        "Email address: test@domain.com", 
        "Password: ", 
        "Password (again): ", 
        "\u001b[31;1mThis password is too short. It must contain at least 8 characters.", 
        "This password is too common.", 
        "\u001b[0mBypass password validation and create user anyway? [y/N]: meme", 
        "Password: ", 
        "Password (again): ", 
        "\u001b[31;1mError: Your passwords didn't match.", 
        "\u001b[0mPassword: ", 
        "Password (again): ", 
        "\u001b[31;1mThis password is too short. It must contain at least 8 characters.", 
        "This password is too common.", 
        "\u001b[0mBypass password validation and create user anyway? [y/N]: meme", 
        "Password: ", 
        "Password (again): ", 
        "\u001b[31;1mThis password is too short. It must contain at least 8 characters.", 
        "This password is too common.", 
        "\u001b[0mBypass password validation and create user anyway? [y/N]: meme", 
        "Password: ", 
        "Password (again): ", 
        "\u001b[31;1mThis password is too short. It must contain at least 8 characters.", 
        "This password is too common.", 
        "\u001b[0mBypass password validation and create user anyway? [y/N]: y", 
        "meme", 
        "meme", 
        "Superuser created successfully.", 
        "meme", 
        "meme"
    ]
`

this is an example of what I mean. Then as I case insensitive matched it would keep spamming the password as an answer.

**Pull request merged**
